name: Build Android APK (Godot 4.4 Mono)

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install Godot 4.4 Mono
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.4/mono/godot-linux.64-mono-experimental.zip
          unzip godot-linux.64-mono-experimental.zip -d godot
          sudo mv godot/Godot_v4.4-*_mono_linux_x86_64/Godot_v4.4-*_mono_linux.x86_64 /usr/local/bin/godot
          godot --version

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: 25c

      - name: Configure Export Presets
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          # 解码密钥库文件
          echo "$KEYSTORE_BASE64" | base64 --decode > debug.keystore
          # 修改 export_presets.cfg 中的签名配置
          sed -i 's|package/signed=false|package/signed=true|g' export_presets.cfg
          sed -i "s|debug.keystore|$PWD/debug.keystore|g" export_presets.cfg
          sed -i "s|KEYSTORE_PASSWORD|${{ secrets.KEYSTORE_PASSWORD }}|g" export_presets.cfg
          sed -i "s|KEY_ALIAS|${{ secrets.KEY_ALIAS }}|g" export_presets.cfg
          sed -i "s|KEY_PASSWORD|${{ secrets.KEY_PASSWORD }}|g" export_presets.cfg

      - name: Export Android APK
        run: |
          godot --headless --export-release Android ./android-release.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: ./android-release.apk
